# 1. Working with a new dataset: Animals-10

## 1.1 Import Libraries

In [16]:
import os
import pathlib
import numpy as np
import matplotlib.pyplot as plt
import kagglehub
import tensorflow as tf

from sklearn.model_selection import train_test_split

## 1.2 Import Dataset

In [17]:
# Download latest version
path = kagglehub.dataset_download("alessiocorrado99/animals10")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'animals10' dataset.
Path to dataset files: /kaggle/input/animals10


## 1.3 Check Dataset

In [18]:
data_dir = pathlib.Path(path) / "raw-img"

print("Data directory:", data_dir)
print("Folders inside data_dir:", os.listdir(data_dir))

Data directory: /kaggle/input/animals10/raw-img
Folders inside data_dir: ['cavallo', 'pecora', 'elefante', 'gatto', 'scoiattolo', 'gallina', 'ragno', 'mucca', 'cane', 'farfalla']


## 1.4 Check Class Names and Counts

In [19]:
class_names = sorted([folder.name for folder in data_dir.iterdir() if folder.is_dir()])

print("Number of classes:", len(class_names))
print("Class names:", class_names)

Number of classes: 10
Class names: ['cane', 'cavallo', 'elefante', 'farfalla', 'gallina', 'gatto', 'mucca', 'pecora', 'ragno', 'scoiattolo']


In [20]:
for class_name in class_names:
    class_folder = data_dir / class_name
    image_count = len(list(class_folder.glob("*")))
    print(class_name, ":", image_count)

cane : 4863
cavallo : 2623
elefante : 1446
farfalla : 2112
gallina : 3098
gatto : 1668
mucca : 1866
pecora : 1820
ragno : 4821
scoiattolo : 1862


## 1.5 Collect image paths and labels

In [21]:
image_paths = []
labels = []

for label_index, class_name in enumerate(class_names):
    class_folder = data_dir / class_name

    for img_path in class_folder.glob("*"):
        if img_path.suffix.lower() in [".jpg", ".jpeg", ".png"]:
            image_paths.append(str(img_path))
            labels.append(label_index)

image_paths = np.array(image_paths)
labels = np.array(labels)

print("Total images:", len(image_paths))
print("Total labels:", len(labels))

print("Example image path:", image_paths[0])
print("Example label:", labels[0])
print("Example class name:", class_names[labels[0]])

Total images: 26179
Total labels: 26179
Example image path: /kaggle/input/animals10/raw-img/cane/OIP-6p-HHjhphvPW9vf63Gg_jAHaGQ.jpeg
Example label: 0
Example class name: cane


## 1.6 Spliting Dataset: train 80 /val 10 /test 10

In [22]:
x_train, x_temp, y_train, y_temp = train_test_split(
    image_paths,
    labels,
    test_size=0.20,
    random_state=42,
    stratify=labels
)

x_val, x_test, y_val, y_test = train_test_split(
    x_temp,
    y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

print("x_train:", len(x_train))
print("x_val:", len(x_val))
print("x_test:", len(x_test))

print("y_train:", len(y_train))
print("y_val:", len(y_val))
print("y_test:", len(y_test))

x_train: 20943
x_val: 2618
x_test: 2618
y_train: 20943
y_val: 2618
y_test: 2618


In [23]:
print("Train label distribution:")
print(np.bincount(y_train))

print("Validation label distribution:")
print(np.bincount(y_val))

print("Test label distribution:")
print(np.bincount(y_test))

Train label distribution:
[3890 2098 1157 1690 2478 1334 1493 1456 3857 1490]
Validation label distribution:
[486 263 144 211 310 167 187 182 482 186]
Test label distribution:
[487 262 145 211 310 167 186 182 482 186]


## 1.7 One-Hot Label

In [24]:
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train, num_classes=10)
y_val = to_categorical(y_val, num_classes=10)
y_test = to_categorical(y_test, num_classes=10)

print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

(20943, 10)
(2618, 10)
(2618, 10)


## 1.7 Save Split Data

In [25]:
import os
import numpy as np

project_dir = "/content/drive/MyDrive/Colab Notebooks/w3_group-6-cnn-image-classification"

# Create subfolders
data_dir = os.path.join(project_dir, "data")
os.makedirs(data_dir, exist_ok=True)

# Save path
split_data_path = os.path.join(data_dir, "animals10_split_data.npz")

# Save train / validation / test split
np.savez(
    split_data_path,
    x_train=x_train,
    x_val=x_val,
    x_test=x_test,
    y_train=y_train,
    y_val=y_val,
    y_test=y_test,
    class_names=np.array(class_names)
)

print("Split data saved to:", split_data_path)

Split data saved to: /content/drive/MyDrive/Colab Notebooks/w3_group-6-cnn-image-classification/data/animals10_split_data.npz
